watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: true
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "active_window",
      ]
      center: [
        "media",
        "komorebi_active_layout",
        "komorebi_workspaces",
        "clock",
        "weather",
        "cpu",
        "memory",
      ]
      right: [
        "systray",
        "language",
        "notifications",
        "wifi",
        "volume",
        "battery",
        "power_menu",
      ]
widgets:
  ### LEFT
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 60
      monitor_exclusive: true
      callbacks:
        on_left: "do_nothing"
  ### CENTER
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
      max_field_size:
        label: 50
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        play: "\uf04b"
        pause: "\uf04c"
        # prev_track: "\ue892"
        # next_track: "\ue893"
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 50
        show_source: false
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{layout_name}"
      layouts: ["bsp", "columns", "rows", "grid", "vertical_stack", "horizontal_stack", "ultrawide_vertical_stack", "right_main_vertical_stack"]
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: "toggle_layout_menu"
        on_middle: "toggle_layout_menu"
        on_right: "toggle_layout_menu"
      layout_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      # label_offline: "Komorebi Offline"
      # label_workspace_btn: "\udb81\udc3d"
      # label_workspace_active_btn: "\udb81\udc3e"
      # label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: true
        hide_floating: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M} <span>\u2022</span> {%a, %d/%m}"
      label_alt: "{%d/%m/%Y %H:%M:%S}"
      callbacks:
        on_left: "toggle_label"
        on_right: "do_nothing"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      api_key: "<REPLACE_ME>"
      update_interval: 5000
      hide_decimal: true
      location: "<REPLACE_ME>"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        default: "\uebaa"
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue302"
        cloudyNight: "\ue32e"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
      weather_card:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      # label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 1000
      callbacks:
        on_left: "do_nothing"
        # on_left: "toggle_label"
      # histogram_icons: [
      #   "\u2581",
      #   "\u2581",
      #   "\u2582",
      #   "\u2583",
      #   "\u2584",
      #   "\u2585",
      #   "\u2586",
      #   "\u2587",
      #   "\u2588"
      # ]
      # histogram_num_columns: 8
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 1000
      callbacks:
        on_left: "toggle_label"
  ### RIGHT
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf078"
      label_expanded: "\uf054"
      label_position: "left"
      icon_size: 14
      # pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_label"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf0a2</span> {count}"
      hide_empty: true
      callbacks:
        on_left: "toggle_notification"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "<span>{wifi_icon}</span> {wifi_name} ({wifi_strength}%)"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c explorer ms-availablenetworks:"
        on_right: "toggle_label"
      wifi_icons: [
        "\udb82\udd2f",
        "\udb82\udd1f",
        "\udb82\udd22",
        "\udb82\udd25",
        "\udb82\udd28"
      ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons: [
        "\ueee8",
        "\uf026",
        "\uf027",
        "\uf027",
        "\uf028"
      ]
      audio_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:apps-volume"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% ({time_remaining})"
      charging_options:
        icon_format: "{charging_icon}"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\udb81\udc25"
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 250
      button_row: 5
      buttons:
        shutdown: ["\udb81\udc25", "Shut Down"]
        restart: ["\uead2", "Restart"]
        sleep: ["\udb82\udd04", "Sleep"]
        lock: ["\uf023", "Lock"]
        signout: ["\udb80\udf43", "Sign Out"]
        cancel: ["\udb81\udf3a", "Cancel"]